apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp1
  namespace: application
spec:
  interval: 1m
  chart:
    spec:
      chart: ./heml_charts/demo2
      version: '22.1+19'
      sourceRef:
        kind: GitRepository
        name: Myapplicationcharts
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml      
  values:
    image:
      tag: New-tag
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yml
    - kind: Secret
      name: helm-secrets
      valuesKey: secrets.yml
