apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: application
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmcharts/charts/nginx
      version: '22.1+19'
      sourceRef:
        kind: GitRepository
        name: nginx
        namespace: application
      interval: 1m

