apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: application
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmcharts/charts/nginx
      version: '1.16.0'
      sourceRef:
        kind: GitRepository
        name: nginx
        namespace: flux-system
      interval: 1m

